spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://47.93.4.111:3306/questionnaire?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver

# log日志配置
logging:
  config: classpath:log4j2-dev.xml
  level:
    com.demo: debug


